### PR TITLE
Spm

### PR DESCRIPTION
**Pull request by yuriygavrilenko**
spm interface added
imports fixed
example updated

### CODE REVIEW

**Comment by yakovshkolnikov** [comment]
No reason to keep `Sources/DashdevsNetworking/Classes/.gitkeep`

**Comment by yakovshkolnikov** [comment]
It's bad practice to have lowercased classes and file names: `dashdevsnetworkingTests`

**Review by yakovshkolnikov — COMMENTED** [review]
Change `dashdevsnetworkingTests` class and file name, otherwise all good)

**Comment by yuriygavrilenko** [comment]
> Change `dashdevsnetworkingTests` class and file name, otherwise all good)

fixed

**Pull request merged**
